### ISSUE TITLE
Custom service types?

### ISSUE THREAD

**Issue by drozzy** [4pcbr/ex_slp_tk#4]
Is there a way to register a service with a custom type? E.g. "printer"?

**Comment by icanhazbroccoli** [comment]
There is none so far, but sounds like a reasonable feature request :-)

**Comment by osdrv** [comment]
A new version containing the feature has been published: https://hex.pm/packages/ex_slp/0.1.2.
In order to specify the service type provide it like:
```elixir
ExSlp.Service.register(service: "printer")
```
De-registration should be executed using the same service type:
```elixir
ExSlp.Service.deregister(service: "printer")
```
For more details see the doc ref: https://hexdocs.pm/ex_slp/ExSlp.Service.html#register/0 and please don't hesitate to ask any questions if any.
Closing the issue for now.
